.PHONY: test-wagahai
test-wagahai:
	@echo "  === unidic_cwj ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_cwj
	@echo "  === unidic_cwj_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_cwj_neologd
	@echo "  === unidic_csj ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_csj
	@echo "  === unidic_csj_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_csj_neologd
	@echo "  === ipadic ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d ipadic
	@echo "  === ipadic_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d ipadic_neologd
	@echo "  === jumandic ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d jumandic

.PHONY: test-wagahai-disp
test-wagahai-disp:
	@echo "  === unidic_cwj ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_cwj -O disp
	@echo "  === unidic_cwj_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_cwj_neologd -O disp
	@echo "  === unidic_csj ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_csj -O disp
	@echo "  === unidic_csj_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_csj_neologd -O disp
	@echo "  === ipadic ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d ipadic -O disp
	@echo "  === ipadic_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d ipadic_neologd -O disp
	@echo "  === jumandic ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d jumandic -O disp

.PHONY: test-wagahai-full
test-wagahai-full:
	@echo "  === unidic_cwj ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_cwj -O full
	@echo "  === unidic_cwj_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_cwj_neologd -O full 
	@echo "  === unidic_csj ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_csj -O full
	@echo "  === unidic_csj_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d unidic_csj_neologd -O full
	@echo "  === ipadic ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d ipadic -O full
	@echo "  === ipadic_neologd ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d ipadic_neologd -O full
	@echo "  === jumandic ==="
	@echo "吾輩は猫である" | python3 -m mecab_cli -d jumandic -O full
